"""Trading signal domain model."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from enum import StrEnum


class SignalType(StrEnum):
    """Supported trading signal directions."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CANCEL = "CANCEL"


@dataclass(frozen=True, slots=True)
class TradingSignal:
    """Signal generated by a strategy."""

    signal_id: str
    strategy_id: str
    strategy_name: str
    symbol_code: str
    signal_type: SignalType
    price: Decimal
    quantity: Decimal
    confidence: Decimal
    timestamp: datetime
    reason: str = ""
